#ifndef _CAN_DATA_H_
#define _CAN_DATA_H_

#include "ch.h"

typedef struct
{
    // Infinity packet IDs
    CAN_PACKET_INFINITY_STATUS = 0x00,
    CAN_PACKET_INFINITY_SET_CURRENT,
    CAN_PACKET_INFINITY_SET_DUTY_CYCLE,
    CAN_PACKET_INFINITY_SET_SPEED,
    // Battman packet IDs
    CAN_PACKET_BATTMAN_STATUS,
    CAN_PACKET_BATTMAN_VOLTAGE,
    CAN_PACKET_BATTMAN_CURRENT,
    CAN_PACKET_BATTMAN_SOC,
    CAN_PACKET_BATTMAN_RTCC,
    CAN_PACKET_BATTMAN_SHUTDOWN
} CANPacketID;

#endif /* _CAN_DATA_H_ */
